### ISSUE TITLE
heartbeat fails to connect, add retry?

### ISSUE THREAD

**Issue by leonblueconic** [opsgenie/opsgenie-heartbeat#4]
We are using heartbeat to monitor if certain scripts get run every XX minutus. This works quite well except the oghb command occasionally fails to connect to the API service. 

> panic: Post https://api.opsgenie.com/v1/json/heartbeat/send: read tcp 104.20.42.30:443: i/o timeout
> 
> goroutine 1 [running]:
> main.doHttpRequest(0x6ccd50, 0x4, 0x6f01d0, 0x17, 0x0, 0xc20803ca80, 0x0, 0x0, 0x0, 0x0)
>   /tmp/opsgenie-heartbeat-2.0.1/script monitor/src/oghb.go:221 +0x98c
> main.sendHeartbeat()
>   /tmp/opsgenie-heartbeat-2.0.1/script monitor/src/oghb.go:140 +0x157
> main.main()
>   /tmp/opsgenie-heartbeat-2.0.1/script monitor/src/oghb.go:32 +0x137
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
>   /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

or 

> panic: unexpected end of JSON input
> 
> goroutine 16 [running]:
> runtime.panic(0x822bd20, 0x186e7ac0)
>   C:/Go/src/pkg/runtime/panic.c:279 +0xe9
> main.createErrorResponse(0x18544e00, 0x0, 0x200, 0x0, 0x0, 0x0)
>   C:/IdeaWorkspace/OpsGenieClient/utilities/oghb.go:184 +0xc8
> main.sendHeartbeat()
>   C:/IdeaWorkspace/OpsGenieClient/utilities/oghb.go:142 +0x13d
> main.main()
>   C:/IdeaWorkspace/OpsGenieClient/utilities/oghb.go:32 +0x101
> 
> goroutine 19 [finalizer wait]:
> runtime.park(0x805bde0, 0x839490c, 0x83934c9)
>   C:/Go/src/pkg/runtime/proc.c:1369 +0x94
> runtime.parkunlock(0x839490c, 0x83934c9)
>   C:/Go/src/pkg/runtime/proc.c:1385 +0x3f
> runfinq()
>   C:/Go/src/pkg/runtime/mgc0.c:2644 +0xc5
> runtime.goexit()
>   C:/Go/src/pkg/runtime/proc.c:1445
> 
> goroutine 25 [IO wait]:
> net.runtime_pollWait(0xf7786588, 0x72, 0x0)
>   C:/Go/src/pkg/runtime/netpoll.goc:146 +0x62
> net.(_pollDesc).Wait(0x1852e3f8, 0x72, 0x0, 0x0)
>   C:/Go/src/pkg/net/fd_poll_runtime.go:84 +0x48
> net.(_pollDesc).WaitRead(0x1852e3f8, 0x0, 0x0)
>   C:/Go/src/pkg/net/fd_poll_runtime.go:89 +0x46
> net.(_netFD).Read(0x1852e3c0, 0x18540c00, 0x400, 0x400, 0x0, 0xf7785230, 0xb)
>   C:/Go/src/pkg/net/fd_unix.go:232 +0x28d
> net.(_conn).Read(0x18500320, 0x18540c00, 0x400, 0x400, 0x0, 0x0, 0x0)
>   C:/Go/src/pkg/net/net.go:122 +0xc6
> crypto/tls.(_block).readFromUntil(0x1850f180, 0xf7786798, 0x18500320, 0x5, 0x0, 0x0)
>   C:/Go/src/pkg/crypto/tls/conn.go:451 +0xb0
> crypto/tls.(_Conn).readRecord(0x18562000, 0x17, 0x0, 0x0)
>   C:/Go/src/pkg/crypto/tls/conn.go:536 +0x1be
> crypto/tls.(_Conn).Read(0x18562000, 0x1854f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
>   C:/Go/src/pkg/crypto/tls/conn.go:901 +0x140
> net/http.noteEOFReader.Read(0xf7786d18, 0x18562000, 0x1850414c, 0x1854f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
>   C:/Go/src/pkg/net/http/transport.go:1203 +0x62
> net/http.(_noteEOFReader).Read(0x186e79b0, 0x1854f000, 0x1000, 0x1000, 0x8395240, 0x0, 0x0)
>   <autogenerated>:124 +0x98
> bufio.(_Reader).fill(0x186d99e0)
>   C:/Go/src/pkg/bufio/bufio.go:97 +0x14c
> bufio.(_Reader).Peek(0x186d99e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
>   C:/Go/src/pkg/bufio/bufio.go:132 +0xde
> net/http.(_persistConn).readLoop(0x18504120)
>   C:/Go/src/pkg/net/http/transport.go:782 +0x8a
> created by net/http.(_Transport).dialConn
>   C:/Go/src/pkg/net/http/transport.go:600 +0x7e3
> 
> goroutine 23 [sleep]:
> time.Sleep(0x2a05f200, 0x1)
>   C:/Go/src/pkg/runtime/time.goc:39 +0x3f
> net.func·019()
>   C:/Go/src/pkg/net/dnsclient_unix.go:183 +0x57
> created by net.loadConfig
>   C:/Go/src/pkg/net/dnsclient_unix.go:212 +0x12e
> 
> goroutine 26 [select]:
> net/http.(_persistConn).writeLoop(0x18504120)
>   C:/Go/src/pkg/net/http/transport.go:885 +0x296
> created by net/http.(_Transport).dialConn
>   C:/Go/src/pkg/net/http/transport.go:601 +0x7f8

or 

> panic: Post https://api.opsgenie.com/v1/json/heartbeat/send: read tcp 54.244.30.182:443: i/o timeout
> 
> goroutine 16 [running]:
> runtime.panic(0x822d040, 0x18769600)
>   C:/Go/src/pkg/runtime/panic.c:279 +0xe9
> main.doHttpRequest(0x825f608, 0x4, 0x827bec8, 0x17, 0x0, 0x1850e9c0, 0x0, 0x0, 0x0, 0x0)
>   C:/IdeaWorkspace/OpsGenieClient/utilities/oghb.go:219 +0x6de
> main.sendHeartbeat()
>   C:/IdeaWorkspace/OpsGenieClient/utilities/oghb.go:140 +0x106
> main.main()
>   C:/IdeaWorkspace/OpsGenieClient/utilities/oghb.go:32 +0x101
> 
> goroutine 19 [finalizer wait]:
> runtime.park(0x805bde0, 0x839490c, 0x83934c9)
>   C:/Go/src/pkg/runtime/proc.c:1369 +0x94
> runtime.parkunlock(0x839490c, 0x83934c9)
>   C:/Go/src/pkg/runtime/proc.c:1385 +0x3f
> runfinq()
>   C:/Go/src/pkg/runtime/mgc0.c:2644 +0xc5
> runtime.goexit()
>   C:/Go/src/pkg/runtime/proc.c:1445
> 
> goroutine 23 [select]:
> net.func·019()
>   C:/Go/src/pkg/net/dnsclient_unix.go:184 +0x24c
> created by net.loadConfig
>   C:/Go/src/pkg/net/dnsclient_unix.go:212 +0x12e

Might it be possible to add some retry code on network connection or possibly a command line flag to to have heartbeart retry X number of times when it fails?

**Comment by halitokumus** [comment]
Hi, we'll update the plugin to use V2 API, it will hopefully perform better. I'll update again when the release is made.

**Comment by cglrkn** [comment]
Hi, 
We updated the plugin to use V2 API. You are welcome to give it a try. Thanks for your collaboration. 
Best Regards
